# Generated by Django 4.1.7 on 2023-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_user_delete_itemfound_delete_itemlost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
