# Generated by Django 4.1.7 on 2023-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_date_remove_user_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
