# Generated by Django 4.1.7 on 2023-02-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
    ]
