# Generated by Django 4.1.7 on 2023-02-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_image_url'),
        ('items', '0004_user_logged_in'),
        ('items', '0005_remove_item_time'),
    ]

    operations = [
    ]
