# Generated by Django 4.1.7 on 2023-02-28 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_merge_0004_item_image_url_0005_remove_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
