# Generated by Django 4.1.7 on 2023-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
