# Generated by Django 4.1.7 on 2023-02-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_time'),
        ('items', '0009_alter_user_status'),
    ]

    operations = [
    ]
