# Generated by Django 4.1.7 on 2023-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_merge_0007_item_time_0009_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
